"""Добавление колонки total_price в модель User

Revision ID: 073624e7eda7
Revises:
Create Date: 2024-03-07 21:09:39.906853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073624e7eda7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float))

    # ### end Alembic commands ###


